version: "3.9"

services:
  plmomo:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    command:
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - VERSION=${VERSION}
    restart: always
    image: plmomo_v${VERSION}
    container_name: plmomo_v${VERSION}
    ports:
      - ${APP_PORT}:8000
    volumes:
      - .:/code/