mortality_data_dir: "../../../data/mortality"
file_suffix: .xlsx
fact_columns: ['gender', 'region', 'age_group', 'year', 'week']
genders: {
  "MĘŻCZYŹNI": 0, 
  "KOBIETY": 1
}
regions: {
    "PL51": 0,  # Dolnośląskie
    "PL61": 1,  # Kujawsko-pomorskie
    "PL81": 2,  # Lubelskie
    "PL43": 3,  # Lubuskie
    "PL71": 4,  # Łódzkie
    "PL21": 5,  # Małopolskie
    "PL9": 6,   # Mazowieckie - macroregion!
    "PL52": 7,  # Opolskie
    "PL82": 8,  # Podkarpackie
    "PL84": 9,  # Podlaskie
    "PL63": 10, # Pomorskie
    "PL22": 11, # Śląskie
    "PL72": 12, # Świętokrzyskie
    "PL62": 13, # Warmińsko-mazurskie
    "PL41": 14, # Wielkopolskie
    "PL42": 15  # Zachodniopomorskie
}
age_groups: {
  "0 - 4": 0,
  "5 - 9": 1,
  "10 - 14": 2,
  "15 - 19": 3,
  "20 - 24": 4,
  "25 - 29": 5,
  "30 - 34": 6,
  "35 - 39": 7,
  "40 - 44": 8,
  "45 - 49": 9,
  "50 - 54": 10,
  "55 - 59": 11,
  "60 - 64": 12,
  "65 - 69": 13,
  "70 - 74": 14,
  "75 - 79": 15,
  "80 - 84": 16,
  "85 - 89": 17,
  "90 i więcej": 18
}